services:
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: backend_django
    container_name: backend_django
    command: python manage.py runserver 0.0.0.0:8000 # @leontinepaq a changer plus tard??
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
      image: nginx:latest
      container_name: frontend
      ports:
        - "8080:80"  # Port pour accéder au frontend
      volumes:
        - ./frontend:/usr/share/nginx/html:ro  # Serveur de fichiers statiques
      depends_on:
      - backend

volumes:
  db:
    name: postgres_data

secrets:
  postgres_password:
   file: ./secrets/postgres_password.txt