services:
  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: django_backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
          condition: service_healthy

  # frontend:
  #   image: nginx
  #   ports:
  #     - "8080:80"  # Port pour accéder au frontend
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html:ro  # Serveur de fichiers statiques
  #   depends_on:
  #     - backend

# volumes:
#   db:
#     name: db
#     driver: local
#     driver_opts:
#       device: ./data/db
#       o : bind
#       type : none